package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MyEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyEntityAllPropertiesEquals(MyEntity expected, MyEntity actual) {
        assertMyEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertMyEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyEntityAllUpdatablePropertiesEquals(MyEntity expected, MyEntity actual) {
        assertMyEntityUpdatableFieldsEquals(expected, actual);
        assertMyEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyEntityAutoGeneratedPropertiesEquals(MyEntity expected, MyEntity actual) {
        assertThat(expected)
            .as("Verify MyEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyEntityUpdatableFieldsEquals(MyEntity expected, MyEntity actual) {
        assertThat(expected)
            .as("Verify MyEntity relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMyEntityUpdatableRelationshipsEquals(MyEntity expected, MyEntity actual) {
        // empty method
    }
}
